/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import CustomPanels.CirclePicture;
import CustomPanels.RoundedPanel;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Blob;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author 63948
 */
public class FriendListMain extends javax.swing.JFrame {

    /**
     * Creates new form FriendListMain
     */
    public FriendListMain() {
        try {
            initComponents();
            String requestPath = "/imagesIcon/darkCover.jpg";
            ImageIcon RequestIcon = new ImageIcon(getClass().getResource(requestPath));
            Image RequestImage = RequestIcon.getImage();
            Image ScaledRequest = RequestImage.getScaledInstance(480, 180, Image.SCALE_SMOOTH);
            ImageIcon ScaledRequestIcon = new ImageIcon(ScaledRequest);
            txtCoverPhoto.setIcon(ScaledRequestIcon);
            
            String profilePath = "imagesIcon/coolAvatar.png";
//        ImageIcon profileIcon = new ImageIcon(getClass().getResource(profilePath));
//        Image profileImage = profileIcon.getImage();
//        CirclePicture circleProfile = new CirclePicture();
//        BufferedImage circularProfile = circleProfile.makeCircularImage((BufferedImage) profileImage);
//        
//        Image ScaledProfile = circularProfile.getScaledInstance(76, 76, Image.SCALE_SMOOTH);
//        ImageIcon ScaledProfileIcon = new ImageIcon(ScaledProfile);
//        txtProfilePicture.setIcon(ScaledProfileIcon);

BufferedImage profileImage = ImageIO.read(getClass().getResource(profilePath));

// Create a circular image
CirclePicture circleProfile = new CirclePicture();
BufferedImage circularProfile = circleProfile.makeCircularImage(profileImage);

// Scale the circular image
Image ScaledProfile = circularProfile.getScaledInstance(76, 76, Image.SCALE_SMOOTH);
ImageIcon ScaledProfileIcon = new ImageIcon(ScaledProfile);
txtProfilePicture.setIcon(ScaledProfileIcon);

//
//        
//        Blob imageBlob = rs.getBlob("profile_picture");
//            InputStream inputStream = imageBlob.getBinaryStream();
//            BufferedImage image = ImageIO.read(inputStream);
//            CirclePicture circleImage = new CirclePicture();
//            BufferedImage circularImage = circleImage.makeCircularImage(image);
//
//            Image scaledImage = circularImage.getScaledInstance(43, 43, Image.SCALE_SMOOTH);
//            ImageIcon icon = new ImageIcon(scaledImage);



txtName.setText("Haer Yve Wyert");
txtBio.setText("HAHAHAHHA I have no bio, what you think");
txtUsername.setText("@nays1");
        } catch (IOException ex) {
            Logger.getLogger(FriendListMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtProfilePicture = new javax.swing.JLabel();
        txtCoverPhoto = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        txtBio = new javax.swing.JLabel();
        txtUsername = new javax.swing.JLabel();
        jPanel3 = new RoundedPanel(15);
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(27, 39, 48));
        jPanel1.setMaximumSize(new java.awt.Dimension(466, 371));
        jPanel1.setMinimumSize(new java.awt.Dimension(466, 371));
        jPanel1.setPreferredSize(new java.awt.Dimension(466, 371));

        jPanel2.setBackground(new java.awt.Color(27, 39, 48));
        jPanel2.setMaximumSize(new java.awt.Dimension(466, 234));
        jPanel2.setMinimumSize(new java.awt.Dimension(466, 234));
        jPanel2.setPreferredSize(new java.awt.Dimension(466, 234));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtProfilePicture.setText("jLabel2");
        txtProfilePicture.setMaximumSize(new java.awt.Dimension(76, 76));
        txtProfilePicture.setMinimumSize(new java.awt.Dimension(76, 76));
        txtProfilePicture.setPreferredSize(new java.awt.Dimension(76, 76));
        jPanel2.add(txtProfilePicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 150, -1, -1));

        txtCoverPhoto.setText("jLabel1");
        txtCoverPhoto.setMaximumSize(new java.awt.Dimension(466, 180));
        txtCoverPhoto.setMinimumSize(new java.awt.Dimension(466, 180));
        txtCoverPhoto.setPreferredSize(new java.awt.Dimension(466, 180));
        jPanel2.add(txtCoverPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtName.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        txtName.setForeground(new java.awt.Color(230, 234, 236));
        txtName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtName.setText("jLabel3");

        txtBio.setBackground(new java.awt.Color(190, 203, 193));
        txtBio.setForeground(new java.awt.Color(157, 167, 172));
        txtBio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBio.setText("jLabel1");

        txtUsername.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(115, 130, 144));
        txtUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtUsername.setText("jLabel1");

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Unfriend");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBio, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBio)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FriendListMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FriendListMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FriendListMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FriendListMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FriendListMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel txtBio;
    private javax.swing.JLabel txtCoverPhoto;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtProfilePicture;
    private javax.swing.JLabel txtUsername;
    // End of variables declaration//GEN-END:variables
}
